Run all tests
jobrad-gmbh/odoo pull request #34
Opened 2024-10-21 06:30 UTC by jhelfferich

With these modifications, the pipeline will run all Odoo tests on the branch. I have limited the tested modules to the ones installed in the JobRad production system.

2024-10-21 08:21 UTC, borna-ng requested changes
Second `docker compose` command has an invalid tag specified `/base/account`. I assume it should be `/base,/account`.

https://github.com/jobrad-gmbh/odoo/actions/runs/11434716121/job/31809204451#step:4:1970

2024-10-21 08:21 UTC, borna-ng commented on tests/run_tests.sh
> +docker compose -f tests/docker-compose.yml down -v
A little bit more robust and slightly more readable:

```suggestion
function cleanup() {
    docker compose -f tests/docker-compose.yml down -v
}

trap cleanup EXIT

docker compose -f tests/docker-compose.yml up -d

echo "---*** Running Odoo tests at_install ***---"
docker compose -f tests/docker-compose.yml exec odoo ./odoo-bin -d test --addons-path=addons,odoo/addons \
    -i base,account \
    --test-enable --test-tags=-post_install \
    --stop-after-init

echo "---*** Running Odoo tests post_install ***---"
docker compose -f tests/docker-compose.yml exec odoo ./odoo-bin -d test --addons-path=addons,odoo/addons \
    --test-enable --test-tags=/base,/account \
    --stop-after-init

docker compose -f tests/docker-compose.yml down -v
```

2024-10-21 08:21 UTC, borna-ng commented on tests/run_tests.sh
Shouldn't we have a list of modules that we actively use in production?

2024-10-21 10:33 UTC, jhelfferich commented on tests/run_tests.sh
> +docker compose -f tests/docker-compose.yml down -v
:thinking: This isn't the latest version of this file. I must have accidentally reverted that...

Nonetheless, great suggestions. I will incorporate them.

2024-10-21 11:56 UTC, jhelfferich commented on tests/run_tests.sh
Yes, and I used that. But I accidentally reverted back to my initial test, where I used just 2 modules to refine the script. Now, it is ready for re-testing.

2024-10-22 10:29 UTC, borna-ng approved these changes
Works very well 🚀

I just have a couple of improvement suggestions

2024-10-22 10:29 UTC, borna-ng commented on pyproject.toml
> +phonenumbers = "8.13.47"
If we need `phonenumbers` package only for testing I would suggest moving it into a separate group (e.g. `[tool.poetry.group.testing.dependencies]`) and making that group optional. We have a similar setup in [odoo-addons-jobrad](https://github.com/jobrad-gmbh/odoo-addons-jobrad/blob/354eabf55cb3f0032025a8b1aec19b303319b165/pyproject.toml#L107).

2024-10-22 10:29 UTC, borna-ng commented on tests/run_tests.sh
> +account,\
It would probably make sense to load the list of modules from a file.

2024-10-22 10:29 UTC, borna-ng commented on poetry.lock
Our suggested way of adding a dependency is to run `poetry lock` with `--no-update` flag. That way we don't get unexpected version updates of subdependencies.

2024-10-22 10:29 UTC, borna-ng commented on .github/workflows/main.yaml
> +          bash tests/run_tests.sh
It would be cool to have the file executable.

2024-10-22 11:38 UTC, jhelfferich commented on pyproject.toml
> +phonenumbers = "8.13.47"
Great suggestion :+1: Done.

2024-10-22 11:39 UTC, jhelfferich commented on tests/run_tests.sh
> +account,\
Done

2024-10-22 11:39 UTC, jhelfferich commented on poetry.lock
Done

2024-10-22 11:39 UTC, jhelfferich commented on .github/workflows/main.yaml
> +          bash tests/run_tests.sh
Done

2024-10-22 11:40 UTC, merged